.\" Manpage for organon.
.\" Contact franco.c.colombino@gmail.com to correct errors or typos.
.TH man 8 "08 september 2015" "0.1.9" "organon man page"

.SH NAME
Organon \- Package manager that focus on pentest tools

.SH SYNOPSIS
usage: organon [-h] [-a] [-v] [-i I [I ...]] [-r R [R ...]] [--dependencies] [--config] [-u] [-s S] [-l] [--clean]

.SH DESCRIPTION
Organon program focuses on automating the download, installation and compilation of pentest tools from source

.SH REQUIREMENTS
  
  1. Python >=2.7 or >=3.4
  2. Ruby >=1.9
  3. bundler
  4. Gems: mysql, colorize, nokogiri
  5. GNU/Linux system based on Debian and Arch


.SH TESTED ON

  * Ubuntu 14.04 x86_64
  * Ubuntu 14.10 x86_64
  * Debian 7.8 Wheezy
  * Debian 8 Squeezy
  * Elementary OS Luna
  * Linux Mint 17.1
  * Manjaro (unstable)

.SH OPTIONS
organon -h 
Shows help

organon -l 
Lists all the availables tools to install

organon -s [PACKAGE]
Search for an specific package

organon -i [PACKAGE]
Install an specific package

organon -r [PACKAGE]
Remove an specific package
       --dependencies
       Remove package dependencies
       --config
       Remove package configuration files

organon -a
Shows README file

organon -v
Shows tool version

organon -u
Search and download updates for Organon

organon --clean
Clean .cache directory

.SH EXAMPLES
organon -i aircrack-ng reaver cangibrina

organon -s hydra

organon -l

organon -r nmap

organon -r nmap --dependencies --config

.SH AUTHORS
  * Fnkoc
  * Maximoz

.SH VISIT THE DEVELOPMENT PAGE
https://github.com/maximozsec/organon
http://organon.ddns.net

.SH BUGS
Please, open an Issue at github if find one
