.\" Manpage for organon.
.\" Contact franco.c.colombino@gmail.com to correct errors or typos.
.TH man 8 "08 september 2015" "0.2.1" "organon man page"

.SH NAME
Organon \- Package manager that focus on pentest tools

.SH SYNOPSIS
usage: organon [-h] [-a] [-v] [-i I [I ...]] [-r R [R ...]] [--deps] [--conf]
               [-U] [-u] [-S] [-s S] [-L] [--clean] [--yes]


.SH DESCRIPTION
Organon is a program that focuses on automating the download, installation and compilation of pentest tools from source

.SH REQUIREMENTS
  
  1. Python >=2.7 or >=3.4
  2. GNU/Linux system based on Debian and Arch


.SH TESTED ON

  * Debian 8 Wheezy
  * Manjaro
  * Arch Linux

.SH OPTIONS
  -h, --help     show this help message and exit
  -a, --about    About this tool
  -v, --version  Show version and exit
  -i I [I ...]   Install packages
  -r R [R ...]   Remove packages
  --deps         Remove dependencies (use with -r)
  --conf         Remove configuration files (use with -r)
  -U             Update Organon
  -u             Update packages
  -S             Synchronize database
  -s S           Search for packages
  -L             List all packages available
  --clean        Clean Organon's cache
  --yes          Assume yes to all questions


organon -h

Shows help

organon -a

Shows MAN file

organon -v
Shows version

organon -i [PACKAGE]

Install an specific package

organon -r [PACKAGE]

Remove an specific package
       --dependencies
       Remove package dependencies
       --config
       Remove package configuration files

organon -U

Search and download updates for Organon

organon -u

Search and download updates for installed packages

organon -S [PACKAGE]

Synchronizes database between server and client

organon -s [PACKAGE]

Search for an specific package

organon -L

Lists all the availables tools to install

organon --clean

Clean /var/cache/organon directory

.SH EXAMPLES
organon -i aircrack-ng reaver cangibrina

organon -i aircrack-ng reaver cangibrina --yes

organon -s scanner

organon -S

organon -L

organon -r nmap

organon -r nmap --deps --conf

.SH AUTHORS
  * Fnkoc

.SH DEVELOPMENT PAGE
https://fnk0c.github.io/organon

https://github.com/fnk0c/organon

.SH BUGS
Please, open an Issue at github if find one
